# Configuration de Base

general:
  rf: 0.04
  conf_level: 0.95
  price_start_year: 2010

simulation:
  simulations: 1000
  years: 20
  frequency: "daily"

frontier:
  total_weight: 100
  min_weight: 0
  max_weight: 100
  weight_increment: 10
  num_sims: 50
  years: 10
  frequency: "monthly"
